[package]
name = "kley"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = { version = "2" }
pest_derive = { version = "2" }
#inkwell = { version = "0.5.0", features = ["llvm18-0-prefer-static"] } 
